swift-crypto 2.x upgrade
apple/swift-package-manager pull request #3759
Opened 2021-09-20 21:42 UTC by yim-lee

Motivation:
swift-crypto v2.x has breaking BoringSSL API changes. We don't want to upgrade to v2 just yet (at least until it's out of beta), but we need to be able to test v2 readily.

Modifications:
- API changes for swift-crypto v2: https://github.com/apple/swift-package-manager/commit/c1be158d24b9014cac6700cc4ade0cccbcf17096 from https://github.com/apple/swift-package-manager/pull/3731 
- `CRYPTO_v2` flag to allow coexistence of v1 and v2 code and make it easier to test v2: https://github.com/apple/swift-package-manager/commit/e8d39eae5ca3e3eae76dc8ec46e7b740a559c55a

I verified locally that package collection tests pass with swift-crypto 1.1.6 and 2.0.0-beta.2 (with `CRYPTO_v2`) on macOS and Linux.

2021-09-20 21:43 UTC, yim-lee commented
@swift-ci please test

2021-09-20 22:02 UTC, compnerd requested changes
Taking another look at the diffs I'm really torn now.  Why not actually switch to the opaque pointers early?  The only difference that will be required then is to explicitly convert the typed pointer to an opaque pointer.  That should be possible to do with the existing `.init`s.

2021-09-20 22:34 UTC, yim-lee commented
> Taking another look at the diffs I'm really torn now. Why not actually switch to the opaque pointers early?

Not sure how to handle this: https://github.com/apple/swift-package-manager/pull/3759/files#diff-dd2607cfda1c066e7514a4010d4b54213f0130731655ddd9169243a943fbbd7bR104

2021-09-21 01:37 UTC, yim-lee commented on Package.swift
> +]
How about https://github.com/apple/swift-package-manager/pull/3759/commits/b83b7c34e7291c0b7676ad28017cda33de1ce44c?

2021-09-21 04:22 UTC, compnerd commented on Package.swift
> +]
Yeah, that is basically what I was thinking

2021-09-21 04:24 UTC, compnerd commented
Ah, right - I was thinking of it in C where the conversion would be permitted through aliasing, but not in Swift.

2021-09-22 22:56 UTC, yim-lee commented
@swift-ci please smoke test

2021-09-23 08:57 UTC, yim-lee commented
@swift-ci please smoke test

2021-09-23 16:56 UTC, yim-lee commented
@swift-ci please smoke test

2021-09-24 18:24 UTC, yim-lee commented
@compnerd Do you have any other comments?

2021-09-29 19:52 UTC, tomerd approved these changes
not familiar with the boring ssl apis aspect but the changes seems reasonable to me

2021-09-29 20:12 UTC, abertelrud reviewed
LGTM

2021-09-29 20:13 UTC, abertelrud approved these changes

2021-09-30 20:02 UTC, yim-lee commented
@compnerd I had to dismiss your previous review so I can proceed with merging, but please feel free to comment if you have any other questions or concerns. I cann create follow-up PRs.

2021-09-30 20:02 UTC, merged