[5.6] Mark the SwiftPM 5.6 branch as a release branch
apple/swift-package-manager pull request #4015
Opened 2022-01-13 08:35 UTC by abertelrud

Mark the SwiftPM 5.6 branch as a release branch.

### Motivation

As happens with every release, the development bit in SwiftPM needs to be turned off in the release branch so that it disallows use of 999.0 package manifest tools versions.  This also causes `swift package --version` to show the version without a `-dev` suffix.

### Modifications

- change `development` from `true` to `false` in SwiftVersion.swift

rdar://87535197

2022-01-13 08:35 UTC, abertelrud commented
@swift-ci test

2022-01-13 17:01 UTC, tomerd commented
@swift-ci test linux

2022-01-13 18:55 UTC, tomerd commented on Sources/PackageDescription/PackageDependency.swift
> +    @available(_PackageDescription, introduced: 5.6)
this should stay 999

2022-01-13 18:55 UTC, tomerd commented on Sources/PackageDescription/PackageDependency.swift
> +    @available(_PackageDescription, introduced: 5.6)
this should stay 999

2022-01-13 18:55 UTC, tomerd commented on Sources/PackageDescription/PackageRequirement.swift
> +    @available(_PackageDescription, introduced: 5.6)
this should stay 999

2022-01-13 18:55 UTC, tomerd commented on Sources/PackageDescription/PackageDependency.swift
> +    @available(_PackageDescription, introduced: 5.6)
this should stay 999

2022-01-13 18:56 UTC, tomerd commented on Sources/PackageDescription/PackageDependency.swift
> +    @available(_PackageDescription, introduced: 5.6)
this should stay 999

2022-01-13 18:56 UTC, tomerd commented on Sources/PackageDescription/PackageDependency.swift
> +    @available(_PackageDescription, introduced: 5.6)
this should stay 999

2022-01-13 18:57 UTC, tomerd requested changes
the registry manifest should stay 999 as its not public feature yet

2022-01-13 19:28 UTC, neonichu approved these changes

2022-01-13 21:58 UTC, abertelrud commented
> the registry manifest should stay 999 as its not public feature yet

Oh right, of course — I moved too quickly and mistook these for the `branch: "foo"` instead of `requirement: .branch("foo")` changes.  I'll undo them.

2022-01-13 22:01 UTC, abertelrud commented
@swift-ci please test

2022-01-13 23:26 UTC, tomerd approved these changes

2022-01-14 00:41 UTC, abertelrud commented
@swift-ci please test

2022-01-14 04:40 UTC, abertelrud commented
Hmm...
```
/Users/buildnode/jenkins/workspace/swift-package-manager-PR-macos/swiftpm/Sources/PackageDescription/PackageDescriptionSerialization.swift:170:30: error: 'RegistryRequirement' is unavailable
18:50:59 extension Package.Dependency.RegistryRequirement: Encodable {
18:50:59                              ^~~~~~~~~~~~~~~~~~~
18:50:59 /Users/buildnode/jenkins/workspace/swift-package-manager-PR-macos/swiftpm/Sources/PackageDescription/PackageRequirement.swift:195:17: note: 'RegistryRequirement' was introduced in PackageDescription 999
18:50:59     public enum RegistryRequirement {
18:50:59                 ^
```

I may have misremembered how we build PackageDescription and PackagePlatform — I didn't think they were built at 999.0, but it's possible, so even release versions can have unreleased types.

Putting this on draft while I look up how we did this for 5.5.

2022-01-14 06:14 UTC, abertelrud commented
I forgot that the PackageDescription and PackagePlugin still gets _compiled_ with 999.0 so that all code can be used — code that uses them gets compiled with the tools version of the package in question.

I have restored this to do the same as we did for 5.5.

2022-01-14 06:14 UTC, abertelrud commented
@swift-ci test

2022-01-14 15:55 UTC, abertelrud commented
@swift-ci test linux

2022-01-15 01:13 UTC, airspeedswift approved these changes

2022-01-15 01:54 UTC, merged