Fix llbuild package name for SWIFTCI_USE_LOCAL_DEPS
apple/swift-package-manager pull request #4138
Opened 2022-02-14 17:46 UTC by keith

Without this fix when this var is set I see:

```
'SwiftPM' /path/to/oss-swift/swiftpm: error: 'swiftpm' dependency on '/path/to/oss-swift/llbuild' has an explicit name 'swift-llbuild' which does not match the name 'llbuild' set for '/path/to/oss-swift/llbuild'
```

2022-02-14 17:47 UTC, keith commented
Maybe my checkout state is invalid somehow?

2022-02-14 17:59 UTC, tomerd requested changes
we normally do not use `SWIFTCI_USE_LOCAL_DEPS` mode for dependencies unless we _need_ to make changes to those as well, and even then you can always change the dep to path based instead of url based. 

in cases we do decide to use `SWIFTCI_USE_LOCAL_DEPS` we check out `swift-llbuild` into `llbuild` since this is how our CI does things (for historical reasons) see https://github.com/apple/swift-package-manager/blob/main/CONTRIBUTING.md#the-bootstrap-script

2022-02-14 18:08 UTC, keith commented
I believe I have the setup you're describing:

```
% git remote -v
origin  https://github.com/apple/swift-llbuild.git (fetch)
origin  https://github.com/apple/swift-llbuild.git (push)
% pwd
/Users/ksmiley/dev/oss-swift/llbuild
```

But I believe the problem is the mismatch with this `llbuild`, not the repo name? https://github.com/apple/swift-llbuild/blob/25333daca549aed69004c9b3d4c6b69d3f32d1d0/Package.swift#L9

2022-02-15 05:41 UTC, tomerd commented
@Keith which version of swift are you using?

2022-02-15 05:57 UTC, keith commented
Ah 5.5 aka stable Xcode. If it's fixed later we can close

2022-02-15 06:41 UTC, tomerd commented
and you see this when you build with the command line or through Xcode?

2022-02-15 06:44 UTC, keith commented
Command line. Just `swift build` with this var set. It sounds unexpected so I can debug more

2022-02-15 17:06 UTC, tomerd commented
this validation was removed in https://github.com/apple/swift-package-manager/pull/3687 so 5.6

2022-02-15 18:21 UTC, keith commented
Thanks, sorry for the noise!

2022-02-15 18:21 UTC, closed without merging