Improve speed of finding cycles
apple/swift-package-manager pull request #5628
Opened 2022-06-25 11:55 UTC by mpsnp

Significantly improve speed of finding cycles in dependency tree

### Motivation:

At the moment, if dependencies are composed to layers, depending on graph size, it can take minutes and even hours to validate that there are no cycles. Take a look at [this issue]()

### Modifications:

Cache already checked graph nodes and reuse results in subsequent visits.

### Result:

This modification improved complexity to O(n) instead of O(n!). So package graph of 100 layers with 100 nodes in each layer is checked in 1-2seconds instead of hours.

2022-06-25 18:54 UTC, tomerd requested changes
is the verbosity change intentional?

2022-06-25 20:34 UTC, mpsnp commented
@tomerd excuse me, don’t get what you mean. Which verbosity?

2022-06-25 20:36 UTC, mpsnp commented
Okay, you mean to use `validManifests` instead of `validPackages`?

2022-06-25 20:40 UTC, mpsnp commented
Actually I think I’ll replace this func by the one from swift-tools-support-core.

2022-06-26 22:33 UTC, tomerd commented
@mpsnp i mean the changes to the plugin runner. they seem accidental?

2022-06-26 22:34 UTC, tomerd commented
wrt to using tools-support-core, our goal is to deprecate that library, so leaning on the SwiftPM version is preferred

2022-06-28 09:10 UTC, mpsnp commented
Yeah, that's why i was confused :) 

Will update PR today, with unit tests, small naming fixes and checks that nothing else uses function from tools-support-core

2022-10-28 00:27 UTC, closed without merging

2022-10-28 00:27 UTC, tomerd commented
looks like this was done via https://github.com/apple/swift-package-manager/pull/5839/

2022-10-28 00:27 UTC, tomerd commented
thanks @mpsnp