SwiftPM plugins cannot determine if output writes to a terminal (#6081)
apple/swift-package-manager pull request #6093
Opened 2023-01-31 22:43 UTC by grynspan

This change sets an environment variable before spawning swift-test if the calling process appears to support ANSI control codes in its output.

### Motivation:

XCTest does not currently consume this information, but having it will allow for improvements to CLI output during testing.

### Modifications:

This change sets an environment variable before spawning swift-test if the calling process appears to support ANSI control codes in its output. This environment variable is then propagated to swift-test/xctest.

### Result:

With this change, the environment variable `XCTEST_ANSI_CONTROL_CODES_SUPPORTED` should be set to `1` in test processes if the calling process (`swift`) supports ANSI control codes (i.e. is a TTY.)

2023-01-31 22:44 UTC, grynspan commented
@swift-ci please test

2023-01-31 22:54 UTC, grynspan commented
@swift-ci please smoke test

2023-02-01 00:18 UTC, neonichu approved these changes
I suspect we want some more checks in here, e.g. potentially not set the env var if `--xunit-output` is being passed, but this seems like a reasonable place to start.

2023-02-01 01:54 UTC, grynspan commented
I'm not sure how to write a test here that can verify it. Any suggestions?

2023-02-01 14:42 UTC, grynspan commented
> I suspect we want some more checks in here, e.g. potentially not set the env var if `--xunit-output` is being passed, but this seems like a reasonable place to start.

At the point where I add the variable, I don't think I have access to that flag anymore, but let me do some digging and see.

2023-02-01 17:07 UTC, grynspan commented
@swift-ci please smoke test macOS

2023-02-01 18:42 UTC, neonichu approved these changes

2023-02-01 19:44 UTC, tomerd requested changes
I would rather find a more idiomatic way than a custom environment variable. what other options do we have?

2023-02-01 20:08 UTC, grynspan commented
> I would rather find a more idiomatic way than a custom environment variable. what other options do we have?

Discussing with @tomerd internally.

2023-03-01 00:38 UTC, grynspan commented
Discussed with @tomerd and he agreed that setting `NO_COLOR` would be a reasonable approach, as it's a _de facto_ standard.

2023-03-01 01:19 UTC, neonichu approved these changes

2023-03-01 02:17 UTC, tomerd approved these changes

2023-03-01 02:17 UTC, merged