Workspace: remove extraneous dependency
apple/swift-package-manager pull request #6282
Opened 2023-03-15 20:42 UTC by compnerd

Clean up the build graph by removing a dependency.

2023-03-15 22:07 UTC, MaxDesiatov approved these changes

2023-03-16 16:33 UTC, neonichu commented
This doesn't seem correct?

```
~/Projects/public/swift-package-manager/Sources/Workspace main*
❯ rg 'import PackageFingerprint'
Workspace+Configuration.swift
15:import PackageFingerprint

Workspace.swift
19:import PackageFingerprint

SourceControlPackageContainer.swift
16:import PackageFingerprint
```

2023-03-16 16:34 UTC, neonichu requested changes
This doesn't seem correct?

```
~/Projects/public/swift-package-manager/Sources/Workspace main*
❯ rg 'import PackageFingerprint'
Workspace+Configuration.swift
15:import PackageFingerprint

Workspace.swift
19:import PackageFingerprint

SourceControlPackageContainer.swift
16:import PackageFingerprint
```

2023-03-16 17:43 UTC, compnerd commented
Hmm, odd, wonder what happened when I originally was cleaning this up.  I was trying to reduce some of the dependency graph so that we could reduce the size of SPM.  But if it's a dependency, then let's keep this as is.

2023-03-16 17:43 UTC, closed without merging