Make group param optional
apple/swift-package-manager pull request #6384
Opened 2023-04-04 22:18 UTC by elsh

Make group param optional to un-break macro packages per https://github.com/apple/swift-package-manager/pull/6365

2023-04-04 22:18 UTC, elsh commented
@swift-ci smoke test

2023-04-04 22:45 UTC, tomerd commented on Sources/CompilerPluginSupport/TargetExtensions.swift
> +        group: TargetGroup?,
`group: TargetGroup? = .package`

2023-04-04 22:47 UTC, tomerd requested changes
this change still makes the argument required, I think it needs a default value

2023-04-04 22:48 UTC, tomerd commented on Sources/CompilerPluginSupport/TargetExtensions.swift
> +        group: TargetGroup?,
this should work like https://github.com/apple/swift-package-manager/pull/6365/files/381f87fda3ec29028aab6891acbaeb24e3398e6e#diff-1c897bc83b443b3ce4e3559868b51b1999bbefb6812fbf97229302be902eecfbR584

2023-04-04 22:48 UTC, tomerd approved these changes

2023-04-04 22:49 UTC, elsh commented
@swift-ci smoke test

2023-04-04 22:50 UTC, DougGregor approved these changes

2023-04-04 23:54 UTC, neonichu approved these changes

2023-04-05 00:33 UTC, elsh commented
@swift-ci smoke test macOS

2023-04-05 03:06 UTC, elsh commented
@swift-ci smoke test windows

2023-04-05 04:53 UTC, merged