Build: centralise the debug information flag handling
apple/swift-package-manager pull request #6665
Opened 2023-06-22 14:48 UTC by compnerd

Rather than spreading out the flag addition across the various different targets, we can control the flags at the SwiftTool level, driving the necessary flag addition at a single site.  This would allow easier management of the flags as we can see the additions uniformly applied.

The test changes alter the expectations for ordering and additional flags being applied for various compilation cases.

2023-06-22 16:25 UTC, MaxDesiatov approved these changes
I assume changes in tests only adjust the order of `-g` expectations? Otherwise LGTM.

2023-06-22 16:26 UTC, compnerd commented
@MaxDesiatov yeah, largely ... a couple of them do *add* additional cases of `-g` being passed, and there is one weird case where there is `-g -g` ... but, yes, the changes in the test expectations are due to the ordering changes.  I'm not sure how many of them actually care about the flags vs are just listing every flag rather than checking explicitly what they are interested in.

2023-06-22 17:57 UTC, neonichu requested changes
I think I am kind of regretting the suggestion to put this logic into `SwiftTool` 😆 

I think at a minimum we have to preserve passing `-g` if someone uses SwiftPM as a library, but I am wondering now whether we should centralize all the logic into the `Build` module and have the debug format be an option in `BuildParameters`.

Sorry about flip-flopping here from my previous suggestion, but I think it's important that we preserve the existing functionality for anyone using SwiftPM as a library. In principle it seems ok for `SwiftTool` to offer additional functionality, but something basic like passing `-g` when building the debug config should come out of the box for clients of the library.

2023-06-22 19:18 UTC, compnerd commented
No need to be sorry, I should have pushed back harder - this is why my initial thought was to put this into the build.  I'm more than happy to do the migration into the right location, but, I don't seem to follow how to get the target information :-(.

2023-06-23 01:16 UTC, compnerd commented
@swift-ci please smoke test

2023-06-23 13:50 UTC, compnerd commented
@swift-ci please smoke test

2023-06-26 15:54 UTC, compnerd commented
@swift-ci please test

2023-06-26 17:06 UTC, compnerd commented
@swift-ci please smoke test

2023-06-26 19:37 UTC, neonichu approved these changes

2023-06-26 20:06 UTC, compnerd commented
@swift-ci please test Windows platform

2023-06-26 21:48 UTC, merged