Tests: special case deserialisation on Windows
apple/swift-package-manager pull request #6980
Opened 2023-10-08 18:11 UTC by compnerd

The content being compared here is the actual file content which is apparently not escaped.  This matches the expectations by explicitly converting the string form of the path rather than the default which escapes it.

2023-10-08 18:11 UTC, compnerd commented
@swift-ci please test

2023-10-08 19:58 UTC, MaxDesiatov requested changes

2023-10-08 19:58 UTC, MaxDesiatov commented on Tests/BuildTests/BuildPlanTests.swift
>          XCTAssertMatch(yamlContents, .contains(inputs.underlying))
If `inputs` type is changed to plain `String`, that will use string interpolation of `AbsolutePath` that calls `_nativePathString(escaped: false)` automatically.

```suggestion
        let inputs = """
            inputs: ["\(AbsolutePath("/Pkg/Snippets/ASnippet.swift"))","\(swiftGetVersionFilePath.escapedPathString)","\(AbsolutePath("/Pkg/.build/debug/Lib.swiftmodule"))"
        """
        XCTAssertMatch(yamlContents, .contains(inputs))
```

2023-10-09 18:54 UTC, MaxDesiatov approved these changes
Thanks!

2023-10-09 22:09 UTC, compnerd commented
@swift-ci please test

2023-10-09 22:13 UTC, MaxDesiatov commented
@swift-ci test windows

2023-10-09 22:50 UTC, compnerd commented
@swift-ci please test

2023-10-09 23:52 UTC, compnerd commented
@swift-ci please test Windows platform

2023-10-10 15:07 UTC, merged