sets file-system as device-agnostic in build manifest  rdar://96403757
apple/swift-package-manager pull request #7052
Opened 2023-11-03 23:48 UTC by pusukuri

sets file-system as device-agnostic in build manifest  

### Motivation:

This is the default mode in XCBuild, and allows incremental builds to work across reboots on APFS. It would also likely address https://github.com/apple/swift-package-manager/issues/4651.

### Modifications:

sets file-system as device-agnostic in build manifest

### Result:

Restarting your system (or inode changes) doesn't invoke unnecessary builds

2023-11-05 20:58 UTC, MaxDesiatov approved these changes

2023-11-05 20:58 UTC, MaxDesiatov commented
@swift-ci test

2023-11-05 21:08 UTC, MaxDesiatov requested changes
`LLBuildManifestTests` need to be adjusted accordingly to make tests pass after the change.

2023-11-06 18:17 UTC, pusukuri commented
Looking into the tests. Thank you, @MaxDesiatov

2023-11-13 15:22 UTC, MaxDesiatov commented
@swift-ci test windows

2023-11-13 15:31 UTC, MaxDesiatov approved these changes
SGTM, thanks!

2023-11-13 17:25 UTC, neonichu commented
@swift-ci test windows

2023-11-14 17:13 UTC, merged