tests: repair `BuildPlanTests.testSnippets` on Windows
apple/swift-package-manager pull request #7082
Opened 2023-11-12 03:46 UTC by compnerd

Escape the path string to match the read content.  This allows this test to pass on Windows improving test coverage.

2023-11-12 03:46 UTC, compnerd commented
@swift-ci please test

2023-11-13 17:25 UTC, neonichu approved these changes

2023-11-13 17:29 UTC, MaxDesiatov requested changes

2023-11-13 17:29 UTC, MaxDesiatov commented on Tests/BuildTests/BuildPlanTests.swift
>          let inputs = """
```suggestion
        let inputs: SerializedJSON = """
```

2023-11-13 17:29 UTC, MaxDesiatov commented on Tests/BuildTests/BuildPlanTests.swift
> +            inputs: ["\(AbsolutePath("/Pkg/Snippets/ASnippet.swift").escapedPathString)","\(swiftGetVersionFilePath.escapedPathString)","\(AbsolutePath("/Pkg/.build/debug/Lib.swiftmodule").escapedPat
Using `SerializedJSON` will escape these paths automatically, assuming you interpolate `AbsolutePath`

```suggestion
            inputs: ["\(AbsolutePath("/Pkg/Snippets/ASnippet.swift"))","\(swiftGetVersionFilePath)","\(AbsolutePath("/Pkg/.build/debug/Lib.swiftmodule"))"
```

2023-11-13 17:30 UTC, MaxDesiatov commented on Tests/BuildTests/BuildPlanTests.swift
>          XCTAssertMatch(yamlContents, .contains(inputs))
We may need to make `underlying` public on `SerializedJSON for this to work.

```suggestion
        XCTAssertMatch(yamlContents, .contains(inputs.underlying))
```

2023-11-13 22:24 UTC, compnerd commented
@swift-ci please test

2023-11-13 22:26 UTC, MaxDesiatov approved these changes
Great, thanks!

2023-11-13 22:26 UTC, MaxDesiatov commented
@swift-ci test windows

2023-11-13 23:08 UTC, compnerd commented
@swift-ci please test Windows platform

2023-11-14 14:57 UTC, merged