build: repair the build on Windows
apple/swift-package-manager pull request #7309
Opened 2024-01-31 17:08 UTC by compnerd

Windows (sometimes?) requires `-parse-as-library` for the `@main` attribute to function. This repairs the SPM build of SPM on Windows.

2024-01-31 17:08 UTC, compnerd commented
@swift-ci please smoke test

2024-01-31 17:36 UTC, neonichu commented
Should we put this into the build system instead? Otherwise, this will be a required addition for any package that uses executable targets on Windows, right?

2024-01-31 17:39 UTC, MaxDesiatov requested changes
This flag is passed automatically to targets on other platforms. We should make this behavior consistent.

2024-01-31 17:41 UTC, compnerd commented
@MaxDesiatov sure, I agree that would be nice, but I would like to repair the build first before fixing issues as I cannot test.  Alternatively, I would be okay with a change like that if we add the complete build (there are tools missing) to the CMake build and add XCTest support as well so that you can run the test suite without SPM.

2024-01-31 21:11 UTC, compnerd commented
@swift-ci please test

2024-02-07 18:46 UTC, MaxDesiatov commented
I assume this can be closed now that https://github.com/apple/swift-package-manager/pull/7322 is merged?

2024-02-07 22:17 UTC, compnerd commented
Likely - if not, we can always restore it.

2024-02-07 22:17 UTC, closed without merging