Add VisionOS platform support to `PIF.PlatformFilter`
apple/swift-package-manager pull request #7448
Opened 2024-04-10 04:41 UTC by Ryu0118

#### Motivation:
In the process of generating PIF, I identified a missing case for VisionOS in the implementation of the `[PackageConditionProtocol].toPlatformFilters()`, which led to assertionFailure when Package's platforms included VisionOS. 

#### Modifications:
- Added a new case `.visionOS` in the switch statement within the `toPlatformFilters()` extension for `[PackageCondition]`. 
- Added a new static property `visionOSFilters` within `PIF.PlatformFilter` to define filters specific to VisionOS.

#### Result:
With these changes, PIFBuilder can now generate PIF without errors for packages that include VisionOS as a target

2024-04-10 06:58 UTC, jakepetroules commented on Sources/XCBuildSupport/PIFBuilder.swift
> +            case .visionOS:
Can you move this case up below watchOS?

2024-04-10 07:03 UTC, jakepetroules requested changes
Thank you for your contribution! I left comments requesting a couple of small changes that need to be addressed.

2024-04-10 07:03 UTC, jakepetroules commented on Sources/XCBuildSupport/PIFBuilder.swift
> +        .init(platform: "visionos"),
This needs to add "xros" or Xcode won't pick up the filters correctly. For example:

```swift
public static let visionOSFilters: [PIF.PlatformFilter] = [
    .init(platform: "xros"),
    .init(platform: "xros", environment: "simulator"),
    .init(platform: "visionos"),
    .init(platform: "visionos", environment: "simulator")
]
```

2024-04-11 02:18 UTC, MaxDesiatov commented
@swift-ci test

2024-04-11 02:57 UTC, jakepetroules approved these changes
Looks great, thanks!

2024-04-12 21:59 UTC, merged