fix: bundlePath of ClangTarget to using C99ExtendedIdentifier
apple/swift-package-manager pull request #7645
Opened 2024-06-07 16:27 UTC by NakaokaRei

### Motivation:

When attempting to access a ClangTarget resource bundle from Objective-C’s `SWIFTPM_MODULE_BUNDLE` where the package or target name contains “-”, a crash occurred.

For instance, in the following `Package.swift`, the generated bundle resource is named `SampleObjc-Package_SampleObjc-Target.bundle`, but `SWIFTPM_MODULE_BUNDLE` tries to access `SampleObjc_Package_SampleObjc_Target.bundle`.
```
import PackageDescription

let package = Package(
    name: "SampleObjc-Package",
    products: [
        .library(
            name: "SampleObjc-Target",
            targets: ["SampleObjc-Target"]),
    ],
    targets: [
        .target(
            name: "SampleObjc-Target",
            path: "Sources/SampleObjc",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
```

This means that createResourcesBundle uses `target.bundlePath` for the filename, which is originally generated from the `potentialBundleName` below.:
```
let potentialBundleName = self.manifest.displayName + "_" + potentialModule.name
```

Therefore, when accessing a resource bundle with “-” in the package or target name, the access string uses `c99Name` (where “-” is replaced with “_”), but the actual generated resource bundle name does not replace “-”, leading to a mismatch and crash.

### Modifications:

Hence, this PR changes the resource bundle name (bundlePath) to use `c99Name`.

### Result:

After this change, the resource bundle names will use C99-compliant identifiers, ensuring consistency between the generated bundle resource name and the name accessed via `SWIFTPM_MODULE_BUNDLE`. This will prevent crashes when accessing resource bundles with package or target names that contain hyphens (”-”).

2024-06-10 14:44 UTC, MaxDesiatov requested changes
Would you mind adding a test that ensures this behavior doesn't regress? Thanks!

2024-06-12 18:21 UTC, MaxDesiatov commented
@NakaokaRei to elaborate, you can follow https://github.com/apple/swift-package-manager/blob/main/Tests/BuildTests/BuildPlanTests.swift. Construct a mock package manifest and generate a build plan for it, checking that correct options and paths are generated in the build plan.

2024-06-15 10:03 UTC, NakaokaRei commented
@MaxDesiatov 
Thanks for the information about adding unit test. However, I  just realized this bug only happens in Xcode. I created a this repository to reproduce this bug.
https://github.com/NakaokaRei/Objc-Resources-Package

In this repo, I created simple objective-c target named "Objc-Resources-Package" having resources. And in the case of running test at Xcode or using `xcodebuild` command, this bug will be reproduced. Bud in the case of running test using `swift test` command, even though objective-c target having "-" in name, the test will be successful.

I guess this is because of the difference of generated `resource_bundle_accessor.m` between Xcode and Swift Package Manager. So I am thinking the bug should be fixed at Xcode side instead of this pr. What do you think ??

2024-06-15 14:36 UTC, MaxDesiatov commented
If the bug is not reproducible on CLI with either of SwiftPM subcommands like `swift build` or `swift test`, then this PR should be closed. Xcode is a closed-source project and its development is not tracked in the SwiftPM repository.

2024-06-15 14:39 UTC, NakaokaRei commented
Okay. I close this PR. And submitted feed back assistant about Xcode.

2024-06-15 14:39 UTC, closed without merging

2026-11-15 04:18 UTC, fang-ling commented
@NakaokaRei Hi! Any updates from the Xcode team since then? I'm still experiencing this issue in Xcode 26.6. Thanks!

2026-11-15 14:36 UTC, MaxDesiatov commented
> Hi! Any updates from the Xcode team since then? I'm still experiencing this issue in Xcode 26.6. Thanks!

Is this reproducible for you with Xcode 27.2 or 27.3 beta? Also, are you able to reproduce it on the command line with SwiftPM's new build system?

2026-11-15 15:01 UTC, fang-ling commented
Thanks for replying @MaxDesiatov, I'll try the newer versions of Xcode as well as SwiftPM's new build system, hopefully sometime around next week.